package comun.dominio;
// Generated 11-feb-2016 10:30:59 by Hibernate Tools 4.0.0

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String localidad;

	public Equipo() {
	}

	public Equipo(String nombre, String localidad) {
		this.nombre = nombre;
		this.localidad = localidad;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Equipo [id=" + id + ", nombre="
				+ nombre + ", localidad=" + localidad + "]";
	}

}
