package comun.dominio;
// Generated 11-feb-2016 10:30:59 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Partido generated by hbm2java
 */
public class Partido implements java.io.Serializable {

	private Integer id;
	private Integer equipo_local;
	private Integer equipo_visitante;
	private Integer goles_local;
	private Integer goles_visitante;
	private Integer jornada;
	
	
	public Partido() {
	}

	public Partido(Integer equipo_local, Integer equipo_visitante, Integer goles_local, Integer goles_visitante,
			Integer jornada) {
		super();
		this.equipo_local = equipo_local;
		this.equipo_visitante = equipo_visitante;
		this.goles_local = goles_local;
		this.goles_visitante = goles_visitante;
		this.jornada = jornada;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the equipo_local
	 */
	public Integer getEquipo_local() {
		return equipo_local;
	}

	/**
	 * @param equipo_local the equipo_local to set
	 */
	public void setEquipo_local(Integer equipo_local) {
		this.equipo_local = equipo_local;
	}

	/**
	 * @return the equipo_visitante
	 */
	public Integer getEquipo_visitante() {
		return equipo_visitante;
	}

	/**
	 * @param equipo_visitante the equipo_visitante to set
	 */
	public void setEquipo_visitante(Integer equipo_visitante) {
		this.equipo_visitante = equipo_visitante;
	}

	/**
	 * @return the goles_local
	 */
	public Integer getGoles_local() {
		return goles_local;
	}

	/**
	 * @param goles_local the goles_local to set
	 */
	public void setGoles_local(Integer goles_local) {
		this.goles_local = goles_local;
	}

	/**
	 * @return the goles_visitante
	 */
	public Integer getGoles_visitante() {
		return goles_visitante;
	}

	/**
	 * @param goles_visitante the goles_visitante to set
	 */
	public void setGoles_visitante(Integer goles_visitante) {
		this.goles_visitante = goles_visitante;
	}

	/**
	 * @return the jornada
	 */
	public Integer getJornada() {
		return jornada;
	}

	/**
	 * @param jornada the jornada to set
	 */
	public void setJornada(Integer jornada) {
		this.jornada = jornada;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Partido [id=" + id + ", equipo_local=" + equipo_local + ", equipo_visitante=" + equipo_visitante
				+ ", goles_local=" + goles_local + ", goles_visitante=" + goles_visitante + ", jornada=" + jornada
				+ "]";
	}
	
	
}
